Dynamic page
Bhekisile/capstone-project pull request #3
Opened 2023-04-27 18:31 UTC by Bhekisile

Add data to JavaScript file
Add toggleShow function to JavaScript
Add images for the desktop version
Deploy the project
Add style
Update README file
The video presenting the features of the project (https://www.loom.com/share/3ee1e1ecb8264c10a945a5fba87da41c)

2023-04-28 12:29 UTC, NahnahAJ requested changes
## Project Status: CHANGES REQUIRED :recycle: 
Hi @Bhekisile , 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!
<img src="https://media4.giphy.com/media/VlqzeaRnhCvPLfrSh6/giphy.gif"/>

## Highlights
- Good commit messages :heavy_check_mark: 
- Good use of the `.gitignore` file :heavy_check_mark: 
- Nice Design :heavy_check_mark: 
- Linters well setup and passing :heavy_check_mark: 
- Good use of GitHub flow :heavy_check_mark: 
- Content personalized :heavy_check_mark: 

## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you take them into account as they can make your code better._

You can also consider:
- N/A

Cheers, and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-04-28 12:29 UTC, nahnahdev commented on README.md
> +- [Live Demo Link](https://www.loom.com/share/e3e80835d23b4b07a54f5cfa00e8c495)
- [ ] Great job so far @Bhekisile :muscle: You've done some impressive work. There are just a few adjustments you need to make and you'll be on your way to the next module :wink: 
- [ ] First of all, I noticed that this link leads to the video presentation and not to the `Live Demo ` of your project so I will suggest that you deploy your project using GitHub pages and include the link to your deployed project here instead of the `Loom video`. :+1: 
- [ ] For the `Loom Video`, you can create a new header in your readme with the title `Video Description` or something similar and under that header you can put the video presentation link :100:  or you can just include the video presentation link in your Pull request description as mentioned in the Project Requirements :+1: 
- [ ] However, after watching your video, I must commend you on showing the desktop view and what you're proud of building but you only mentioned that the site can adapt to mobile screens as well but you didn't show that in the video.
- I will suggest that you record another video and this time ensure that you show how your project can adapt to smaller screen sizes as well :100: 
- Project Requirement
![image](https://user-images.githubusercontent.com/102699958/234902585-3fe11986-8c87-4943-9a57-6c3adc31b137.png)

2023-04-28 12:29 UTC, nahnahdev commented on README.md
> +I would like to thank Cindy Shin on Behance and Microverse and the team for this opportunity.
- [ ] Great job giving acknowledgment to Cindy Shin. But I will suggest you include the link to her work or to her page on Behnace to appropriately give credit to her like so:

`[Cindy Shin](https://www.behance.net/adagio07) the [author of the original design](https://www.behance.net/gallery/29845175/CC-Global-Summit-2015), as required by the [Creative Commons License](https://creativecommons.org/licenses/).`

2023-04-28 12:29 UTC, nahnahdev commented on index.html
> +            <h3>School Of Science</h3>
- [ ] Please style this heading as seen in the Original design. You will have to increase the `font size` and `font-weight` of your design :+1: 
- [ ] I also noticed that the short orange horizontal bar below the title is a little darker compared to that of the original design. Please apply the right color to that bar as well as all the other ones used in your project :100: So as to meet this requirement:
![image](https://user-images.githubusercontent.com/102699958/235134263-5c551a4f-6d70-4a20-a177-0ff87a5f80c7.png)

| Your Design | The Original Design |
|--------|--------|
| ![image](https://user-images.githubusercontent.com/102699958/235128813-6c8a9893-eeec-499e-869d-879f3356a48a.png) | ![image](https://user-images.githubusercontent.com/102699958/235128766-f0971864-52f8-486f-ba15-6326f49d049e.png) |

2023-04-28 12:29 UTC, nahnahdev commented on index.html
> +                </div>
- [ ] Great job styling this part of your project. I will only suggest that you ensure that the contents of each card have enough spacing on the top and bottom of each card as seen in the design :+1: Currently, the content of your cards looks very close to the top and bottom edges :+1: 
- [ ] From the Behance design, you can see that the cards have a hover effect which you're currently missing so kindly include that as well :100: 
- [ ] The mobile design for this section looks great so please ensure that you don't mess with it when fixing the desktop styles :wink: 

| Your Design | The Original Design |
|--------|--------|
| ![image](https://user-images.githubusercontent.com/102699958/235135805-494ca29a-bdb8-499d-8d51-f5e6fe3329d1.png) | ![image](https://user-images.githubusercontent.com/102699958/235135875-8bfc4df5-5d12-4730-9859-b688f2b6d27c.png) |

2023-04-28 12:29 UTC, nahnahdev commented on index.html
> +        </article>
- [ ] Your `Featured speakers` section looks great there are just a few style adjustments you'll have to make. However, per the Project requirements, this section needs to be generated dynamically from javascript. To do this, you'll need to create an array of objects that contains the data you want to display in the section. Then, you can use JavaScript to dynamically generate the HTML elements based on the data in the array. :+1: 
- [ ] So kindly remove all this hardcoded content you have here and add them through javascript so as to meet all the project requirements :100: 
- Here's an example of how you might do this:
- Create an array of objects that contains the data for each section. Each object should have at least the name, role, description, and image url of the speaker. For example: :100: 

```
const sections = [
{
  name: "Julia Leda", 
  role: "President of Young pirates of Europe", 
  description: "European ingetration, political democracy, and participation of ...", 
  photo: "image_url_here"
},
  {
  name: "Julia Leda", 
  role: "President of Young pirates of Europe", 
  description: "European ingetration, political democracy, and participation of ...", 
  photo: "image_url_here"
}
// Add more sections as needed
];

```



- Project Requirements
![image](https://user-images.githubusercontent.com/102699958/235138822-b2357b68-c41f-4475-80b2-085e87cc9e6c.png)

- [ ] I have also noted the areas that need to be changed in the image below :wink: 
- Your Design
![image](https://user-images.githubusercontent.com/102699958/235138572-b988f552-aa7e-467a-938c-95076ec29f73.png)

- The Original Design
![image](https://user-images.githubusercontent.com/102699958/235138691-d02eb02f-4098-4e9e-8285-579b3fc9eb04.png)

2023-04-28 12:29 UTC, NahnahAJ commented on index.html
> +            <p>2015 Creative Commons South Africa. Some Rights Reserved.</p>
- [ ] Great job with the footer :+1: I will only suggest a small style adjustment of this text which I have highlighted in the image below :100: 
- Your Design
![image](https://user-images.githubusercontent.com/102699958/235143611-62782ad8-5c8d-4f44-981e-4887d7c2a209.png)

- The Behance Design
![image](https://user-images.githubusercontent.com/102699958/235143697-0a25d73b-32bb-4ab9-9612-0c81235bdfe9.png)

2023-04-28 12:29 UTC, nahnahdev commented on about.html
> +                </div>
- [ ] For the bottom section, I noticed that you added the two images, but they don't have text centered over them as seen in the design and they are also missing the orange color overlayed over the images so kindly include these in your design as well :+1: 
- [ ] Please ensure that you do same for the mobile view as well :100: 

- Your Design
![image](https://user-images.githubusercontent.com/102699958/235145195-d81843e8-0726-4290-884d-9b58deceb58d.png)

- The Behance Design
![image](https://user-images.githubusercontent.com/102699958/235145292-deb72e00-91fa-422b-9b6a-6b0a573195ff.png)

2023-04-28 12:29 UTC, NahnahAJ commented on about.html
> +</body>
- [ ] I also noticed that on the `About page,` you're missing the `footer` section. So kindly include that in your design as well and remove the `Partners Section` so your design looks similar to the original design :100: 
- [ ] I also noticed that you have a horizontal scroll effect in your design so kindly fix this as well :100: 
- Your Design
![image](https://user-images.githubusercontent.com/102699958/235146159-16853f11-81f7-48da-b7a8-d10129619b0b.png)

- The Behance design
![image](https://user-images.githubusercontent.com/102699958/235146406-a7ec3c45-b420-4675-8c72-d1b6a7861f3d.png)

2023-04-28 12:29 UTC, NahnahAJ commented on about.html
> +        </nav>
- [ ]  I noticed that you don't have a link back to the `Home Page` when on the `About Page` of the mobile view so kindly fix this as well :100: 
- Your design on the `About Page`
![image](https://user-images.githubusercontent.com/102699958/235146873-00ac6616-0efd-4caa-8f32-f0cb529243c0.png)

2023-04-29 13:41 UTC, franclobo requested changes
Hi @Bhekisile, 

# Suggested changes

![soClose](https://user-images.githubusercontent.com/58642949/235304379-ac6914b3-aa3c-44b9-81af-6d78820869aa.gif)

Great work on making the changes 👏 
You've done well implementing some of the requested changes, but there are still some which aren't addressed yet.

## Highlights

- No linter errors ✔️ 
- Descriptive PR ✔️ 
- Professional documentation ✔️ 
- Good UI ✔️ 

## Suggested changes
_Check the comments under the review._

- [ ] As requested by the last code reviewer we should also highlight some interesting **piece of code** or something you built that you are very proud of. Please 🙏🏽 open your favorite IDE and explain what your favorite piece of code that makes you feel proud of.


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

2023-04-29 13:41 UTC, franclobo commented on styles.css
> +}
- [ ] As requested by the previous code reviewer, in the original design there is a hover effect that turns the border color withe. Please 🙏🏽 add it to be similar to the original design for a better UX.

2023-04-29 13:41 UTC, franclobo commented on styles.css
> +  }
- [ ] Well done doing this section dynamically Kindly ensure that the style is working for the mobile and desktop versions, the next picture is from the desktop version, and the lectures should be in two columns for a better UI 👇🏽 

![image](https://user-images.githubusercontent.com/58642949/235305652-0baa30d5-2935-4f05-b5bc-180f7e3f618f.png)

2023-04-29 13:41 UTC, franclobo commented on about.html
> +            <img class="logo-img desktop" src="./Image/uni-logo1.png" alt="">
- **[OPTIONAL]** It is necessary to have a way to back to the home page from the about page. Please 🙏🏽 create the link as requested in the project requirements for a better UX 👇🏽 

![image](https://user-images.githubusercontent.com/58642949/235305947-b9344ccd-dd3a-42e0-bb94-2320a6860ac8.png)

2023-04-29 19:22 UTC, amejid requested changes
Hi @Bhekisile, 

Great work on making the changes requested by a previous reviewer 👏 
You've done well implementing some of the requested changes, but there are still some which aren't addressed yet.

<img src="https://media1.giphy.com/media/yoOotVRp4JMxVTEgDy/giphy.gif"/>

 ## Highlights
- Linter checks passing ✔️ 
- Good UI design ✔️ 
- Correct use of Github flow ✔️ 

 ## Required Changes ♻️

- [ ] **You did a great job presenting your work. I think you forgot to highlight a piece of code you feel most proud of. Kindly record the video again to include that detail as suggested by the previous reviewer and stated in the project requirements.**

**Project requirements**
![image](https://user-images.githubusercontent.com/17243325/235320563-b4ceefb9-2b0c-488e-a2c2-cc3dc87f5885.png)


## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-04-29 20:10 UTC, Reem-lab approved these changes
# Hi @Bhekisile, 👋🏻👋🏻

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉🔥💯🤩 
<img src="https://media4.giphy.com/media/SYzDscQMN98G0LUHib/giphy.gif"/>

## Highlights ✨✨
- No Linters error ✨
- Followed GitHub flow 🔥
- Great working on the functionlality 💯
- Fully responsive 🔥💯
- Professional README 💯
- Deployed well 🔥
- Great job working on the video presentation and highlight the most thing you proud of 💯💯

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-04-29 20:18 UTC, merged